# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
