# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiekie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AddField(
            model_name='picture',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
